//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2
//! 
pub mod prelude;

pub mod sys_user;
pub mod sys_dept;
pub mod sys_menu;
pub mod sys_position;
pub mod sys_role_menu;
pub mod sys_role;
pub mod sys_user_dept;
pub mod sys_user_position;
pub mod sys_user_role;